### ISSUE TITLE
無法登入

### ISSUE THREAD

**Issue by RaC3M** [HappyGroupHub/FCU-AutoClass#1]
目前使用時，在登入畫面能夠自動輸入帳號密碼但是會無法進入系統，驗證碼等都是有讀取到的，帳號也無誤。

**Comment by HappyGroupHub** [comment]
你好，請附上日誌記錄檔方便我協助你除錯喔！
路徑：FCU-AutoCLass > logs > xxx.txt

**Comment by HappyGroupHub** [comment]
此 [Issue](https://github.com/HappyGroupHub/FCU-AutoClass/issues/1) 因長時間未得到近一步回覆
所以我就先關閉此單了，若有需要歡迎再發問喔~
