### ISSUE TITLE
菜雞詢問

### ISSUE THREAD

**Issue by Grayu5303** [HappyGroupHub/FCU-AutoClass#2]
logs顯示如下
'FCU-AutoClass.exe' is not recognized as an internal or external command,
operable program or batch file.

試過把config.yml刪除得到的回覆也是相同的 請問我是否有漏掉甚麼呢? 懇請開釋

**Comment by HappyGroupHub** [comment]
Hi @Grayu5303 

看起來這個錯誤是因為 `run.bat` 沒有偵測到 `FCU-AutoClass.exe`，因此程式沒有運行起來喔！
請確認一下你的 `FCU-AutoClass.exe` 有沒有被 Windows Defender 偵測成病毒然後清掉了

另外如果確定檔案存在但仍然無法行 `run.bat`，你可以直接執行 `FCU-AutoClass.exe` 來運行搶課程式
但這個方法就不會有後續的 logs 檔案產生，也沒有出錯自動重啟的功能

**Comment by Grayu5303** [comment]
你好~已經可以正常運行了 感謝大大 我的超人

**Comment by HappyGroupHub** [comment]
沒問題~ 使用愉快
