### ISSUE TITLE
登不進去

### ISSUE THREAD

**Issue by yc0331** [HappyGroupHub/FCU-AutoClass#3]
[logs-20240911-155813.txt](https://github.com/user-attachments/files/16960080/logs-20240911-155813.txt)
[logs-20240911-155448.txt](https://github.com/user-attachments/files/16960081/logs-20240911-155448.txt)
[logs-20240911-155415.txt](https://github.com/user-attachments/files/16960082/logs-20240911-155415.txt)
[logs-20240911-155229.txt](https://github.com/user-attachments/files/16960083/logs-20240911-155229.txt)
[logs-20240911-155159.txt](https://github.com/user-attachments/files/16960084/logs-20240911-155159.txt)

不確定是不是給這個 麻煩了

**Comment by HappyGroupHub** [comment]
Hi @yc0331 

這個錯誤是因為程式並沒有成功開啟網頁而導致的
請幫我確認你的電腦有安裝 Google Chrome，並且版本為最新版喔！

**Comment by yc0331** [comment]
有的剛剛重新安裝過一次還是這樣QQ

**Comment by HappyGroupHub** [comment]
抱歉，你遇到的情況我目前沒辦法協助解決，建議你先用其他台電腦運行看看
由於選課時間是有期限的，這應該是短期最好的方法🥲

**Comment by HappyGroupHub** [comment]
Closed with no further response.
