### ISSUE TITLE
不好意思! 想請問一下會有安全上的疑慮嗎? 謝謝!

### ISSUE THREAD

**Issue by henry1121520** [HappyGroupHub/FCU-AutoClass#4]

**Comment by HappyGroupHub** [comment]
Hi @henry1121520 

這個專案的原始碼是開放且供所有人查閱的
不放心的話可以自行將所有 python 程式源碼下載執行喔~

**Comment by HappyGroupHub** [comment]
此 [Issue](https://github.com/HappyGroupHub/FCU-AutoClass/issues/4) 因長時間未得到近一步回覆
所以我就先關閉此單了，若有需要歡迎再發問喔~
