### ISSUE TITLE
下載問題

### ISSUE THREAD

**Issue by chia-y123** [HappyGroupHub/FCU-AutoClass#5]
不好意思，想問問yml的檔案該用什麼程式打開，或者想問是否有安裝的影片可以索取。謝謝

**Comment by HappyGroupHub** [comment]
Hi @chia-y123 

yaml 檔案建議使用軟體 [Notepad++](https://notepad-plus-plus.org/) 進行瀏覽跟編輯
這個軟體除了可以協助你打開不同類型的文字檔案，同時他也是一個開放原始碼的項目可以安心使用
如果你找不到如何安裝可以直接點[這裡下載](https://github.com/notepad-plus-plus/notepad-plus-plus/releases/download/v8.6.9/npp.8.6.9.Installer.x64.exe)，使用教學可以參考[這篇文章](https://today.line.me/tw/v2/article/EDEaaP)

如果你只是想快速使用程式
yaml 檔案可以直接使用 Windows 內建的記事本打開喔！

**Comment by chia-y123** [comment]
> 你好@chia-y123
> 
> yaml文件建議使用軟體[Notepad++](https://notepad-plus-plus.org/)進行瀏覽跟編輯 該軟體另外可以幫助您打開不同類型的文字文件，同時他也是一個開放原始碼的項目可以放心使用 如果您找不到如何安裝可以直接點[這裡下載](https://github.com/notepad-plus-plus/notepad-plus-plus/releases/download/v8.6.9/npp.8.6.9.Installer.x64.exe)，使用教學可以參考[這篇文章](https://today.line.me/tw/v2/article/EDEaaP)
> 
> 如果你只是想快速使用程式 yaml檔案可以直接使用Windows內建的記事本來開啟！


/

> 你好@chia-y123
> 
> yaml文件建議使用軟體[Notepad++](https://notepad-plus-plus.org/)進行瀏覽跟編輯 該軟體另外可以幫助您打開不同類型的文字文件，同時他也是一個開放原始碼的項目可以放心使用 如果您找不到如何安裝可以直接點[這裡下載](https://github.com/notepad-plus-plus/notepad-plus-plus/releases/download/v8.6.9/npp.8.6.9.Installer.x64.exe)，使用教學可以參考[這篇文章](https://today.line.me/tw/v2/article/EDEaaP)
> 
> 如果你只是想快速使用程式 yaml檔案可以直接使用Windows內建的記事本來開啟！

不好意思，那想問記事本編輯完後是直接關掉，在打開cmd嗎?謝謝

**Comment by HappyGroupHub** [comment]
Hi @chia-y123 

填入完 `config.yml` 後記得儲存檔案（按下Ctrl + S）
接下來就可以直接運行 `run.bat` 囉！

**Comment by chia-y123** [comment]
> 你好@chia-y123
> 
> 填入`config.yml`完成後記得儲存檔案（按Ctrl + S） 接下來就可以直接執行`run.bat`囉！

可以了!太謝謝你了!

**Comment by HappyGroupHub** [comment]
沒問題！使用愉快
